#!/usr/bin/env node
/**
 * build-index.mjs — parse docs/book/sections/*.md into docs/book/index.json + index.md,
 * enforcing the Book's structural invariants:
 *   - front-matter (section, title, group) matches filename and headings
 *   - rule ids are LETTER:NUMBER, belong to their section, contiguous 1..N (append-only, never renumber)
 *   - no duplicate rule ids across the whole book
 *   - every section group exists in schema/routing-manifest.json groups
 * Exit 1 on any violation. Run after every book edit.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SECTIONS_DIR = join(ROOT, "docs", "book", "sections");
const MANIFEST = JSON.parse(readFileSync(join(ROOT, "schema", "routing-manifest.json"), "utf8"));

const errors = [];
const sections = [];
const seenRuleIds = new Set();

const files = readdirSync(SECTIONS_DIR).filter((f) => f.endsWith(".md")).sort();
for (const file of files) {
  const text = readFileSync(join(SECTIONS_DIR, file), "utf8");
  const fm = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!fm) { errors.push(`${file}: missing front-matter`); continue; }
  const meta = {};
  for (const line of fm[1].split("\n")) {
    const m = line.match(/^(\w+):\s*(.*)$/);
    if (m) meta[m[1]] = m[2].replace(/^"|"$/g, "");
  }
  const { section, title, group } = meta;
  if (!section || !title || !group) { errors.push(`${file}: front-matter needs section/title/group`); continue; }
  if (!file.startsWith(section + "-")) errors.push(`${file}: filename prefix != section '${section}'`);
  if (!Object.hasOwn(MANIFEST.groups, group)) errors.push(`${file}: group '${group}' not in routing-manifest groups`);
  else if (!MANIFEST.groups[group].includes(section)) errors.push(`${file}: section '${section}' not listed under group '${group}' in routing-manifest`);

  const rules = [];
  const ruleRe = /^## ([A-Z]{1,2}):(\d+)\s*[—–-]\s*(.+)$/gm;
  let m;
  while ((m = ruleRe.exec(text)) !== null) {
    const [, letter, numStr, ruleTitle] = m;
    const id = `${letter}:${numStr}`;
    if (letter !== section) errors.push(`${file}: rule ${id} inside section ${section}`);
    if (seenRuleIds.has(id)) errors.push(`duplicate rule id ${id}`);
    seenRuleIds.add(id);
    rules.push({ id, n: Number(numStr), title: ruleTitle.trim() });
  }
  const nums = rules.map((r) => r.n);
  const expected = Array.from({ length: nums.length }, (_, i) => i + 1);
  if (JSON.stringify(nums) !== JSON.stringify(expected)) {
    errors.push(`${file}: rule numbers not contiguous 1..${nums.length} in order (append-only violated?): [${nums.join(",")}]`);
  }
  if (rules.length === 0) errors.push(`${file}: no rules parsed`);
  sections.push({
    id: section,
    title,
    group,
    file: `sections/${file}`,
    rule_count: rules.length,
    rules: rules.map(({ id, title }) => ({ id, title })),
  });
}

// stable order: single letters A..Z, then double letters AA..
sections.sort((a, b) => (a.id.length - b.id.length) || a.id.localeCompare(b.id));

if (errors.length) {
  console.error(`BOOK INVALID — ${errors.length} error(s):`);
  for (const e of errors) console.error("  - " + e);
  process.exit(1);
}

const index = {
  kind: "book-index",
  generated_by: "tools/build-index.mjs",
  section_count: sections.length,
  rule_count: sections.reduce((s, x) => s + x.rule_count, 0),
  sections,
};
writeFileSync(join(ROOT, "docs", "book", "index.json"), JSON.stringify(index, null, 1) + "\n");

const md = [
  "# The Audit Book — Index",
  "",
  "> Master taxonomy of production-readiness, security, performance, cost, and compliance checks.",
  "> ID format: `<SECTION>:<NUMBER>` (e.g. `A:4`, `AA:3`). **IDs are stable — never renumber; only append.**",
  "> Generated by `tools/build-index.mjs` — do not edit by hand.",
  "",
  `**${index.section_count} sections · ${index.rule_count} rules**`,
  "",
  "| Section | Title | Group | Rules |",
  "|---|---|---|---|",
  ...sections.map((s) => `| [${s.id}](${s.file}) | ${s.title} | ${s.group} | ${s.rule_count} |`),
  "",
];
writeFileSync(join(ROOT, "docs", "book", "index.md"), md.join("\n"));

console.log(`OK: ${index.section_count} sections, ${index.rule_count} rules -> docs/book/index.json + index.md`);
